### PR TITLE
Add ES6 Lint Reporter

### PR DESCRIPTION
**Pull request by mayank-patel**
Pulling in commits form Add ESLint reporter #106 and resolving the merge conflict

### CODE REVIEW

**Comment by jsoverson** [comment]
Thanks @mayank-patel. I'm taking a look at this now.

**Comment by mayank-patel** [comment]
@jsoverson Thanks for looking into the pull request.

**Comment by jsoverson** [comment]
@mayank-patel would you be willing to continue the support of eslint? I can foresee this approach leading to more support issues and I have no time to support v1 when I'm trying to (still) get v2 out, but if you're willing and able to continue the support of (at least) the eslint portion, then I can be ok with the merge.

**Comment by mayank-patel** [comment]
@jsoverson sure happy to help

**Comment by MathRobin** [comment]
Will we be able to disable JSHint if we want ? I hate JSHint and if you use ESLint, jshint is perfectly useless
Thanks for the PR !

**Comment by jsoverson** [comment]
This has been merged, will be published next release.

**Comment by MathRobin** [comment]
Great great :-D

**Comment by mayank-patel** [comment]
@jsoverson do you have any planned date for the next release ?

**Comment by MathRobin** [comment]
No news, bad news ?

For the moment, for those who really need it, you should install plato via npm install a git repo and not a declared package

**Comment by jsoverson** [comment]
This was released as of 1.5 a couple weeks ago. Sorry for not updating the
issue.

**Comment by MathRobin** [comment]
Oh great !! :D
Thanks ! (you should close this issue)

**Comment by robertbaker** [comment]
Needs documentation updated! Will plato.inspect work with it too if we are using this in gulp?

**Comment by robertbaker** [comment]
@mayank-patel @jsoverson

**Comment by derekrjones** [comment]
Thanks @mayank-patel , but I'm having issues with running this

1. old eslint is version `^0.7.4` and is not compatible with newer versions
 - `Error: Definition for rule 'space-before-function-paren' was not found.`
2. updating eslint or removing it (to use eslint up the tree) doesn't seem to work with plugins
 - ` Error: Definition for rule 'angular/ng_controller_name' was not found.`
 - if I remove this rule from .eslintrc, it will run, but does not catch any errors from angular plugin

**Comment by zeuben** [comment]
@derekrjones  +1 -- bunlded eslint is waay out of date.
get loads of `Error: Definition for rule 'comma-dangle' was not found.`
any ideas on how to solve this one cleanly?

**Comment by zeuben** [comment]
Here is my .eslintrc that it does not like:
`
{
    "parser": "babel-eslint",

    "env": {
        "browser": true,
        "node": true,
        "es6": true,
        "mocha": true
    },

    "ecmaFeatures": {
        "arrowFunctions": true,
        "binaryLiterals": true,
        "blockBindings": true,
        "classes": false,
        "defaultParams": true,
        "destructuring": true,
        "forOf": true,
        "generators": true,
        "modules": true,
        "objectLiteralComputedProperties": true,
        "objectLiteralDuplicateProperties": true,
        "objectLiteralShorthandMethods": true,
        "objectLiteralShorthandProperties": true,
        "octalLiterals": true,
        "regexUFlag": true,
        "regexYFlag": true,
        "spread": true,
        "superInFunctions": false,
        "templateStrings": true,
        "unicodeCodePointEscapes": true,
        "globalReturn": true,
        "jsx": true
    },

    "rules": {
        "block-scoped-var": [0],
        "brace-style": [2, "1tbs", { "allowSingleLine": true }],
        "camelcase": [0],
        "comma-dangle": [2, "never"],
        "comma-spacing": [2],
        "comma-style": [2, "last"],
        "complexity": [0, 11],
        "consistent-return": [2],
        "consistent-this": [0, "that"],
        "curly": [2, "multi-line"],
        "default-case": [2],
        "dot-notation": [2, { "allowKeywords": true }],
        "eol-last": [2],
        "eqeqeq": [2],
        "func-names": [0],
        "func-style": [0, "declaration"],
        "generator-star-spacing": [2, "after"],
        "strict": 0,
        "guard-for-in": [0],
        "handle-callback-err": [0],
        "key-spacing": [2, { "beforeColon": false, "afterColon": true }],
        "quotes": [2, "single", "avoid-escape"],
        "max-depth": [0, 4],
        "max-len": [0, 80, 4],
        "max-nested-callbacks": [0, 2],
        "max-params": [0, 3],
        "max-statements": [0, 10],
        "new-parens": [2],
        "new-cap": [0],
        "newline-after-var": [0],
        "no-alert": [2],
        "no-array-constructor": [2],
        "no-bitwise": [0],
        "no-caller": [2],
        "no-catch-shadow": [2],
        "no-cond-assign": [2],
        "no-console": [0],
        "no-constant-condition": [1],
        "no-continue": [2],
        "no-control-regex": [2],
        "no-debugger": [2],
        "no-delete-var": [2],
        "no-div-regex": [0],
        "no-dupe-args": [2],
        "no-dupe-keys": [2],
        "no-duplicate-case": [2],
        "no-else-return": [0],
        "no-empty": [2],
        "no-empty-class": [2],
        "no-empty-label": [2],
        "no-eq-null": [0],
        "no-eval": [2],
        "no-ex-assign": [2],
        "no-extend-native": [1],
        "no-extra-bind": [2],
        "no-extra-boolean-cast": [2],
        "no-extra-parens": [0],
        "no-extra-semi": [1],
        "no-extra-strict": [2],
        "no-fallthrough": [2],
        "no-floating-decimal": [2],
        "no-func-assign": [2],
        "no-implied-eval": [2],
        "no-inline-comments": [0],
        "no-inner-declarations": [2, "functions"],
        "no-invalid-regexp": [2],
        "no-irregular-whitespace": [2],
        "no-iterator": [2],
        "no-label-var": [2],
        "no-labels": [2],
        "no-lone-blocks": [2],
        "no-lonely-if": [2],
        "no-loop-func": [2],
        "no-mixed-requires": [0, false],
        "no-mixed-spaces-and-tabs": [2, false],
        "no-multi-spaces": [2],
        "no-multi-str": [2],
        "no-multiple-empty-lines": [2, { "max": 2 }],
        "no-native-reassign": [1],
        "no-negated-in-lhs": [2],
        "no-nested-ternary": [0],
        "no-new": [2],
        "no-new-func": [2],
        "no-new-object": [2],
        "no-new-require": [0],
        "no-new-wrappers": [2],
        "no-obj-calls": [2],
        "no-octal": [2],
        "no-octal-escape": [2],
        "no-param-reassign": [2],
        "no-path-concat": [0],
        "no-plusplus": [0],
        "no-process-env": [0],
        "no-process-exit": [2],
        "no-proto": [2],
        "no-redeclare": [2],
        "no-regex-spaces": [2],
        "no-reserved-keys": [0],
        "no-restricted-modules": [0],
        "no-return-assign": [2],
        "no-script-url": [2],
        "no-self-compare": [0],
        "no-sequences": [2],
        "no-shadow": [2],
        "no-shadow-restricted-names": [2],
        "no-space-before-semi": [2],
        "no-spaced-func": [2],
        "no-sparse-arrays": [2],
        "no-sync": [0],
        "no-ternary": [0],
        "no-throw-literal": [2],
        "no-trailing-spaces": [2],
        "no-undef": [2],
        "no-undef-init": [2],
        "no-undefined": [0],
        "no-underscore-dangle": [2],
        "no-unreachable": [2],
        "no-unused-expressions": [2],
        "no-unused-vars": [1, { "vars": "all", "args": "after-used" }],
        "no-use-before-define": [2],
        "no-void": [0],
        "no-warning-comments": [0, { "terms": ["todo", "fixme", "xxx"], "location": "start" }],
        "no-with": [2],
        "no-wrap-func": [2],
        "one-var": [0],
        "operator-assignment": [0, "always"],
        "operator-linebreak": [2, "after"],
        "padded-blocks": [0],
        "quote-props": [0],
        "radix": [0],
        "semi": [2],
        "semi-spacing": [2, { "before": false, "after": true }],
        "sort-vars": [0],
        "space-after-keywords": [2, "always"],
        "space-before-function-paren": [2, { "anonymous": "always", "named": "always" }],
        "space-before-blocks": [0, "always"],
        "space-in-brackets": [0, "never", {
            "singleValue": true,
            "arraysInArrays": false,
            "arraysInObjects": false,
            "objectsInArrays": true,
            "objectsInObjects": true,
            "propertyName": false
        }],
        "space-in-parens": [2, "never"],
        "space-infix-ops": [2],
        "space-return-throw-case": [2],
        "space-unary-ops": [2, { "words": true, "nonwords": false }],
        "spaced-line-comment": [0, "always"],
        "strict": [1],
        "use-isnan": [2],
        "valid-jsdoc": [0],
        "valid-typeof": [2],
        "vars-on-top": [0],
        "wrap-iife": [2],
        "wrap-regex": [2],
        "yoda": [2, "never", { "exceptRange": true }]
    }
}
`

**Pull request merged**
