### PR TITLE
Update and tighten dependencies

### PR DESCRIPTION
**Pull request by ilanbiala**

### CODE REVIEW

**Comment by ilanbiala** [comment]
Bump.

**Comment by ilanbiala** [comment]
@jsoverson any issue with this PR?

**Comment by jsoverson** [comment]
Nope, not at all, just haven't been ignoring the deluge of github issues all around due to other responsibilities. I'll try to get these addressed by the end of the weekend.

**Comment by jsoverson** [comment]
@ilanbiala given the ability to work on PRs or attempt progress on v2, i chose v2 instead of taking a look at the current issue/pr list.

If you're willing, i'd still love help from someone managing v1 which will give me the freedom to push forward on v2 and will give you access to merge as you see fit.

**Comment by ilanbiala** [comment]
@jsoverson what are your plans for v1? I'm not sure how much I'll be able to help manage v1 without understanding all the analysis concepts too much.

**Comment by jeffrey-l-turner** [comment]
@jsoverson I'd be happy to manage v1 to get some of these PRs out of the way

**Comment by jsoverson** [comment]
dependencies updated in 1.6.0

**Pull request closed without merging**
